### ISSUE TITLE
Provide CSS style ability

### ISSUE THREAD

**Issue by I2olanD** [joblocal/vue-bucket-loader#17]
Add extractability for css in our VueBucketLoader. Extract-text-webpack-plugin is now in beta and works with webpack 4 and usable with our project.

webpack-contrib/extract-text-webpack-plugin#701 (comment)

I will provide the setup via PR.

**Comment by aholzner** [comment]
@I2olanD Shall we close this pull request?

**Comment by I2olanD** [comment]
@aholzner i guess so :).
