### ISSUE TITLE
possible to list bucket contents before upload?

### ISSUE THREAD

**Issue by vesper8** [joblocal/vue-bucket-loader#23]
I am wondering if there's any plan to retrieve the list of the bucket content prior to the first upload?

Which would also retrieve existing contents not uploaded in this session

I also noticed there's a typo in the docs.. you write :signungUrl="..." but it should be signedUrl=""

So the : is also a typo

And I was only able to import it like this:

```
import VueBucketLoader from '@joblocal/vue-bucket-loader';
```

**Comment by jayhof** [comment]
Hi @vesper8 thanks for your interest and input.

For our use case we just wanted a quick, easy and extendable way of uploading files to a bucket (with a prefix) and sending some data with in a form. So for the purpose this package was developed a revisiting of the uploaded files was not intended.

Which of course doesn't mean it's a bad idea or we don't want it, in fact it's already possible. Whenever your parent component is ready to pass the information of uploaded files to the VueBucketLoader you just reference it and set the ```files``` array.

A simplified implementation, with a few assumptions, would look like this:

```js
// ... your parent component
async mounted() {
  const uploadedFiles = await s3.fetchListOfUploadedFiles('...'); // or whatever the s3 js sdk provides

  // ... probably .map through the array of items fetched from s3

  // ... then pass the array to the files of the VueBucketLoader
  this.$refs.customFileItemBucketLoader.files = [
    {
      file: {
        name: 'test.jpg',
        type: 'image/jpg',
      },
    },
  ];
}
```

**Comment by jayhof** [comment]
I'm closing this as no follow up was posted.
