### ISSUE TITLE
What type of data is expected by the local endpoint?

### ISSUE THREAD

**Issue by RostiMelk** [joblocal/vue-bucket-loader#50]
Other than a presigned url, what type of data is expected by the local endpoint, and in what format?

I am having issues with invalid signature errors, so that's why I am asking.

From the source code it seems like it expects a json with the following:
- postEndpoint
- Signature

Wouldn't the signature already be embedded in the presigned url or am I wrong?

Let me know if my question is unclear as I am quite new to aws.

**Comment by lightblader** [comment]
Hi,

in the response we are expecting the `postEndpoint` (which is normally your S3-Bucket url) and the `signature`, which includes the `fields` from an AWS S3 [presignedPost](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#createPresignedPost-property) request.

For node, our signing endpoint looks similar to

```
import AWS from 'aws-sdk';
 
const client = new AWS.S3(AWS.Config({ region: 'eu-west-1' }));

const presignedPost = await client.createPresignedPost({
  Bucket: S3_BUCKET_NAME,
    Conditions: [
      ['starts-with', '$key', `prefix/`], // Force the S3 key to start with 'prefix/'
    ],
    Fields: {
      key: 'prefix/filename', // set the S3-key (we use variables to set them individually)
    },
    Expires: 60, // Presigned url is valid for 60 seconds
});

return {
  body: {
    signature: presignedPost.fields,
    postEndpoint: `https://s3.eu-west-1.amazonaws.com/${S3_BUCKET_NAME}`,
  },
  statusCode: 200,
}; 
```

Hopefully this is of help to you :)

Best Wishes!

**Comment by RostiMelk** [comment]
Thanks a lot for your help! 
I got the uploads working.
