### ISSUE TITLE
Add emit events for add-file-success and add-file-error.

### ISSUE THREAD

**Issue by RostiMelk** [joblocal/vue-bucket-loader#55]
I would be great to have emit events for when a file has successfully been uploaded, or has failed uploading.

I have submitted https://github.com/joblocal/vue-bucket-loader/pull/51 that adds this feature, but have yet to receive a response.

Thanks.

**Comment by I2olanD** [comment]
@RostiMelk make sure to add tests for this usecase :)

**Comment by RostiMelk** [comment]
@I2olanD Just pushed a new commit that contains tests for this. 👍
